mkdir assets
mkdir assets/css
mkdir assets/images
mkdir assets/scss
mkdir assets/scss/abstracts
touch assets/scss/abstracts/_variables.scss
touch assets/scss/abstracts/_functions.scss
mkdir assets/scss/base
touch assets/scss/base/_reset.scss
touch assets/scss/base/_typography.scss
mkdir assets/scss/components
touch assets/scss/components/_buttons.scss
touch assets/scss/components/_carousel.scss
mkdir assets/scss/layout
touch assets/scss/layout/_navigation.scss
touch assets/scss/layout/_grid.scss
mkdir assets/scss/pages
touch assets/scss/pages/_home.scss
touch assets/scss/pages/_contact.scss
mkdir assets/scss/vendors
touch assets/scss/vendors/_dummy.scss
mkdir assets/scss/themes
touch assets/scss/themes/_theme.scss
touch assets/scss/themes/_admin.scss
echo "\
@import 'abstracts/variables';\n\
@import 'abstracts/functions';\n\
@import 'vendors/dummy';\n\
@import 'base/reset';\n\
@import 'base/typography';\n\
@import 'layout/navigation';\n\
@import 'layout/grid';\n\
@import 'components/buttons';\n\
@import 'components/carousel';\n\
@import 'pages/home';\n\
@import 'pages/contact';\n\
@import 'themes/theme';\n\
@import 'themes/admin';\n\
" > assets/scss/main.scss
touch index.html